#!/bin/bash

PKG_NAME="core-custom-local"
SRC="${HOME}/src"

[ -f "${SRC}/${PKG_NAME}/VERSION" ] || {
  echo "Missing VERSION file: ${SRC}/${PKG_NAME}/VERSION"
  echo "Exiting"
  exit 1
}

. "${SRC}/${SRC_NAME}/VERSION"
PKG_VER=${VERSION}
PKG_REL=${RELEASE}
PKG_PRE="${PKG_NAME}_${PKG_VER}-${PKG_REL}"

DEB="${SRC}/${PKG_NAME}/dist/${PKG_PRE}.deb"

[ -f "${DEB}" ] || {
    echo "$DEB not found."
    for debs in ${SRC}/${PKG_NAME}/dist/${PKG_NAME}_*.deb
    do
      [ "${debs}" == "${SRC}/${PKG_NAME}/dist/${PKG_NAME}_*.deb" ] || {
        echo "Found existing packages:"
        echo "${debs}"
      }
    done
    echo "Exiting."
    exit 1
}

# Versions of apt prior to 1.1 do not support install by Debian filename
# You should probably be running a more recent version of apt
# On these early versions, install with the following:
#
# sudo dpkg -i "${DEB}"
# sudo apt-get install -f

sudo apt install "${DEB}"
