#!/bin/bash
PKG="core-custom-local"
PKG_NAME="core-custom-local"
TOP="usr"
DESTDIR="${TOP}/local"
SRC=${HOME}/src
SUDO=sudo

[ -f "${SRC}/${PKG_NAME}/VERSION" ] || {
  [ -f "/builds/doctorfree/${PKG_NAME}/VERSION" ] || {
    echo "$SRC/$PKG_NAME/VERSION does not exist. Exiting."
    exit 1
  }
  SRC="/builds/doctorfree"
  SUDO=
  GCI=1
}

. "${SRC}/${PKG_NAME}/VERSION"
PKG_VER=${VERSION}
PKG_REL=${RELEASE}

# Subdirectory in which to create the distribution files
OUT_DIR="dist/${PKG_NAME}_${PKG_VER}"

[ -d "${SRC}/${PKG_NAME}" ] || {
  [ -d "/builds/doctorfree/${PKG_NAME}" ] || {
    echo "$SRC/$PKG_NAME does not exist or is not a directory. Exiting."
    exit 1
  }
  SRC="/builds/doctorfree"
  SUDO=
}

cd "${SRC}/${PKG_NAME}"
${SUDO} rm -rf dist
mkdir dist

[ -d ${OUT_DIR} ] && rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}
mkdir ${OUT_DIR}/DEBIAN

echo "Package: ${PKG}
Version: ${PKG_VER}
Section: misc
Priority: optional
Architecture: all
Depends:
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: debhelper (>= 11)
Standards-Version: 4.1.3
Homepage: https://gitlab.com/doctorfree/core-custom-local
Description: Custom package to hold /usr/local as a recognized installation folder
 The Debian packaging system does not recognize /usr/local as a standard installation path" > ${OUT_DIR}/DEBIAN/control

chmod 644 ${OUT_DIR}/DEBIAN/control

for dir in "${TOP}" "${DESTDIR}" "${DESTDIR}/share" "${DESTDIR}/share/man" \
           "${DESTDIR}/share/doc" "${DESTDIR}/bin" "${DESTDIR}/etc" \
           "${DESTDIR}/games" "${DESTDIR}/include" "${DESTDIR}/lib" \
           "${DESTDIR}/sbin" "${DESTDIR}/share/doc/${PKG}" "${DESTDIR}/src" \
           "${DESTDIR}/share/man/man1" "${DESTDIR}/share/man/man2" \
           "${DESTDIR}/share/man/man3" "${DESTDIR}/share/man/man4" \
           "${DESTDIR}/share/man/man5" "${DESTDIR}/share/man/man6" \
           "${DESTDIR}/share/man/man7" "${DESTDIR}/share/man/man8"
do
    [ -d ${OUT_DIR}/${dir} ] || ${SUDO} mkdir ${OUT_DIR}/${dir}
    ${SUDO} chown root:root ${OUT_DIR}/${dir}
done

${SUDO} cp Install ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/Install
${SUDO} cp Uninstall ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/Uninstall
${SUDO} cp AUTHORS ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/AUTHORS
${SUDO} cp LICENSE ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/copyright
${SUDO} cp CHANGELOG.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog
${SUDO} cp README.md ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/README
${SUDO} gzip -9 ${OUT_DIR}/${DESTDIR}/share/doc/${PKG}/changelog

cd dist
echo "Building ${PKG_NAME}_${PKG_VER}-${PKG_REL} package"
${SUDO} dpkg --build ${PKG_NAME}_${PKG_VER} ${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb
